version: "3"

services:
    mongo:
        image: mongo
        container_name: Mongo
        volumes:
            - shared:/home
        networks:
            - shared_network
        ports:
            - "8888:9999"
    httpd:
        image: httpd
        container_name: Httpd
        volumes: 
            - shared:/home
            - .:/home/exemplo
        networks:
            - shared_network
volumes: 
    shared:
networks:
    shared_network: