version: '3'

services:

    postgres:
      container_name: postgres_container
      image: kaiserfrost/newtp2vr:postgres
      environment:
        PGDATA: /data/postgres
      volumes:
         - postgres:/data/postgres
      ports:
        - "6543:5432"
      networks:
        - postgres
      restart: unless-stopped
    auth-service:
      container_name: auth_container
      image: kaiserfrost/newtp2vr:auth
      networks:
        - postgres
        - httpnetwork
        - ftpnetwork
      ports: 
        - "5001:5001"
    httpservice:
      container_name: http_container
      image: kaiserfrost/newtp2vr:http
      networks: 
        - httpnetwork
      ports: 
        - "8001:8001"
      volumes:
        - servervol:/usr/src/http
    ftpservice:
      container_name: ftp_container
      image: kaiserfrost/newtp2vr:ftp
      networks:
        - ftpnetwork
      ports:
        - "21:21"
      volumes:
        - servervol:/usr/src/ftp       
networks: 
    postgres:
    httpnetwork:
    ftpnetwork:
volumes:
  postgres:
  servervol:
    
