version: '3'
services:
  service1:
   image: httpd:latest
   ports:
    - "8080:80"
   volumes:
    - httpd-vol:/usr/local/apache2/
   networks:
    - container-net
volumes:
  httpd-vol:
networks:
  container-net:
